spring:
  profiles:
    active: dev

eureka:
  instance:
    hostname: ${spring.profiles.active}
    instance-id: ${spring.profiles.active}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10003/eureka/,http://localhost:10001/eureka/,http://localhost:10002/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000
    peer-node-read-timeout-ms:  10000


logging:
  level:
    org:
      springframework:
        cloud: debug
    com:
      netflix: debug

---
spring:
  application:
    name: eureka-peer
  profiles: dev

server:
  port: 10003



---
spring:
  profiles: dev1
  application:
    name: eureka-peer2
server:
  port: 10001


---
spring:
   profiles: dev2
   application:
     name: eureka-peer3
server:
  port: 10002


---