server:
  port: 8089

spring:
  application:
    name: spring-cloud-bus
  cloud:
    bus:
      destination: bus-q
      trace:
        enabled: true
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                publisher-confirms: true
      bindings:
        myInput:
          binder: rabbit1
          destination: things1
        myOutput:
          binder: rabbit1
          destination: things1
          ###添加bus的通道配置
        springCloudBusOutput:
          binder: rabbit1
        springCloudBusInput:
          binder: rabbit1