spring:
  datasource:
    url: jdbc:mysql://localhost:3306/panel
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #redis配置信息
  redis:
    cluster:
      nodes: 172.16.91.54:7000,172.16.91.54:7001,172.16.91.54:7002,172.16.91.54:7003,172.16.91.54:7004,172.16.91.54:7005
    timeout: 50000


zookeeper:
  url: 127.0.0.1:2181

management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true