server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:10003/eureka/,http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/
    eureka-connection-idle-timeout-seconds: 60
    enabled: true
spring:
  application:
    name: eureka-clinet
